### ISSUE TITLE
Template works only from current directory

### ISSUE THREAD

**Issue by hryamzik** [inCaller/prometheus_bot#14]
`template_path: "testdata/default.tmpl"` doesn't work.

**Comment by strangeman** [comment]
https://golang.org/pkg/text/template/#Template.ParseFiles

>ParseFiles parses the named files and associates the resulting templates with t. If an error occurs, parsing stops and the returned template is nil; otherwise it is t. There must be at least one file. _**Since the templates created by ParseFiles are named by the base names of the argument files, t should usually have the name of one of the (base) names of the files.**_ If it does not, depending on t's contents before calling ParseFiles, t.Execute may fail. In that case use t.ExecuteTemplate to execute a valid template.

I fixed it. Will push in the same PR with https://github.com/inCaller/prometheus_bot/issues/13
