### ISSUE TITLE
Undefined license

### ISSUE THREAD

**Issue by iavael** [inCaller/prometheus_bot#21]
There's no license defined for this project (or I just didn't find one), so it cannot be used, modified or distributed legally.
Could you please define it?

**Comment by Savemech** [comment]
fyi:
https://help.github.com/articles/licensing-a-repository/
https://stackoverflow.com/questions/4007674/whats-the-default-license-of-code-published-at-github

**Comment by iavael** [comment]
@Savemech I know that (I wrote "so it cannot be used, modified or distributed legally"). But projects are usually published on github to be kinda opensource (in terms of https://opensource.org/osd).
So this issue is about eliminating ambiguity and defining license explicitly.

**Comment by hryamzik** [comment]
@iavael can you just make a PR with MIT/BSD license?
