### ISSUE TITLE
go 1.8.3: function "str_Format_MeasureUnit" not defined

### ISSUE THREAD

**Issue by hryamzik** [inCaller/prometheus_bot#26]
Hey @AndreaGreco, I can see tests failing with go 1.8.3, any ideas how to fix this?
```
Problem reading parsing template file: template: production_example.tmpl:20: function "str_Format_MeasureUnit" not defined
```

**Comment by AndreaGreco** [comment]
This evening i will check this bug.

Thank you for reporting

Andrea

2017-07-05 14:13 GMT+02:00 Roman Belyakovsky <notifications@github.com>:

**Comment by AndreaGreco** [comment]
Today compiled and all works.
I think you could close this
