### ISSUE TITLE
prometheus_bot fails when message too long

### ISSUE THREAD

**Issue by strangeman** [inCaller/prometheus_bot#29]
In some cases, we have very long alert message (for example, we have alert for underreplicated kafka topics, grouped by instance, and entire instance with 40 topics was failed).
When prometheus_bot tries to send the similar message - it fails and flood the channel with `Error sending message, checkout logs` messages.

Telegram API have message length limit - 4096 UTF8 characters (https://core.telegram.org/method/messages.sendMessage). Looks like your bot doesn't check message length.

**Comment by hryamzik** [comment]
Hi @strangeman, I believe that was already implemented in one of [forks](https://github.com/StereoRu/prometheus_bot/commit/2611dfe48363bf4a8df2574796d0306b66553896). Didn't read it carefully but if you decide to make a PR that may be a good starting point. I'll be happy to merge it.

**Comment by strangeman** [comment]
Ok, I'll check them and adopt changes to my PR

**Comment by strangeman** [comment]
PR was merged, I'm closing issue.
