### ISSUE TITLE
Tag releases and regularly publish on Dockerhub

### ISSUE THREAD

**Issue by tholu** [inCaller/prometheus_bot#31]
Can you tag releases and regularly build and publish a Docker Image? Would make it easier to include this in a docker-compose based deployment of prometheus.

**Comment by tholu** [comment]
@hryamzik Thanks for letting me know! If there's nobody else who can, I'll do this on my fork.

**Comment by favadi** [comment]
For anyone just looking for a precompiled binary of this plugin: https://github.com/favadi/prometheus_bot_bin.

**Comment by hryamzik** [comment]
https://github.com/favadi/prometheus_bot_bin/blob/master/.travis.yml#L13

Looks safe, lol.

**Comment by hryamzik** [comment]
I still think this key could be used to put a different binary to your releases using travis in a different repo but that may be wrong.

**Comment by favadi** [comment]
> I still think this key could be used to put a different binary to your releases using travis in a different repo but that may be wrong.

No, you can't reuse this encrypted key in other repositories, Travis will generate a key pair for each repository.
