### ISSUE TITLE
Conflict: can't use getUpdates method while webhook is active

### ISSUE THREAD

**Issue by hotsnow** [inCaller/prometheus_bot#41]
prometheus_bot Version: Latest commit 3767980  on Jul 26

2018/10/05 16:48:41 getUpdates resp: {"ok":false,"error_code":409,"description":"Conflict: can't use getUpdates method while webhook is active"}
2018/10/05 16:48:41 Conflict: can't use getUpdates method while webhook is active
2018/10/05 16:48:41 Failed to get updates, retrying in 3 seconds...

**Comment by hryamzik** [comment]
https://core.telegram.org/bots/api#getting-updates
