### ISSUE TITLE
Not all chat_id's contain `-`

### ISSUE THREAD

**Issue by dmaes** [inCaller/prometheus_bot#63]
I started a private chat with the bot, and got the following message: `Chat id is '12345678'`.
Per README instructions, I then configured alertmanager with webhook url `http://some.host.name/alert/-12345678`, resulting in `Chat not found` error messages from the bot.

Broke my head over this, until I invited the bot into a group chat, and I got a chat_id with `-` included (`Chat id is '-5678901'`), which did work with url `http://some.host.name/alert/-5678901`. Then trying to use the 'private' chat_id without `-` in the url (`http://some.host.name/alert/12345678`) also worked.

So I suggest updating README to something like:

```markdown
### Configuring alert manager

Alert manager configuration file:

- name: 'admins'
  webhook_configs:
  - send_resolved: True
    url: http://127.0.0.1:9087/alert/chat_id

Replace chat_id with the number you got from your bot, ***with everything inside the quotes*** (Some chat_id's start with `-`, so if there is a `-` in your chat_id, make sure to include it in the url). To use multiple chats just add more receivers.
```

**Comment by hryamzik** [comment]
I'd say the word `number` is not correct here. Feel free to fire a PR.
