### ISSUE TITLE
Value nul

### ISSUE THREAD

**Issue by azizzailani** [inCaller/prometheus_bot#76]
why are the type(summary), Instance and description empty?

config template.tmpl:
```
Type: "{{ .CommonAnnotations.description }}"
Summary: "{{.CommonAnnotations.summary}}"
Alertname: "{{ .CommonLabels.alertname }}"
Instance: "{{ .CommonLabels.instance }}"
Severity: {{ .CommonLabels.severity}}
Status:  {{ .Status }}
```
output:
```
Type: ""
Summary: ""
Alertname: "HostOutOfMemory"
Instance: ""
Severity: warning
Status:  firing
```

This happens because every time series is uniquely identified by its metric name and a set of labels. And every unique combination of key-value label pairs represents a new alert for this time series.

**Comment by azizzailani** [comment]
@hryamzik

**Comment by mulderx** [comment]
didn't you try this production_example.tmpl ?

**Comment by azizzailani** [comment]
> didn't you try this production_example.tmpl ?

already, but no output received by telegram

**Comment by hryamzik** [comment]
What's in your rules file?

**Comment by azizzailani** [comment]
my rules
```
name: InstanceDown
expr: up{job="node_exporter"} == 0
for: 1m
labels:
severity: critical
annotations:
description: {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.
summary: Instance {{ $labels.instance }} down @channel 
```

@hryamzik

**Comment by hryamzik** [comment]
Did you take a look at sniffed traffic between alert manager and prometheus bot? Did you try to leave just plain text in summary?

**Comment by ricky-rocky** [comment]
I  also  have  this   problem


template.tmpl 
Type: {{.CommonAnnotations.description}}
Summary: {{.CommonAnnotations.summary}}
Alertname: {{ .CommonLabels.alertname }}
Instance: {{ .CommonLabels.instance }}
Serverity: {{ .CommonLabels.serverity}}
Status:  {{ .Status }}


rule:
    - alert: NodeLowDataDisk
      expr: ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"} ) / node_filesystem_size_bytes{mountpoint="/"} * 100)     >  75 
      for: 2m
      labels:
        severity: critical
      annotations:
        DESCRIPTION: "{{$labels.instance}}: Data disk usage is above 75% (current value is: {{ $value }})"
        SUMMARY: "{{$labels.instance}}: Low data disk space"


TG  output  

Type: 
Summary: 
Alertname: NodeCPUUsage
Instance: 
Serverity: 
Status:  firing

**Comment by ivzyukov** [comment]
you miss spaces after `{{` and before brackets `}}`
