### ISSUE TITLE
[FEATURE REQUEST] Please add a /healthz endpoint

### ISSUE THREAD

**Issue by ArtemKaba** [inCaller/prometheus_bot#78]
Hi!
Thank you for your bot application.
Could you please add the endpoint for readiness probe of your bot.
It would be great if it won't create access log records while do the probe.

**Comment by hryamzik** [comment]
I don't see any reason for a separate endpoint. Just check regular port. I don't think it's going to log these requests but if so you can just use TCP check insteaf of HTTP one.
