### ISSUE TITLE
Automate publish docker image to github registry

### ISSUE THREAD

**Issue by kubitre** [inCaller/prometheus_bot#84]
Hi, I saw that you do not have an automatic build of the project and publication on the github registry, maybe you need help with this? I can issue an MR if you agree

What will it give? People do not have to build the project locally, they can immediately pull this image to their local / production env

**Comment by aminvakil** [comment]
FWIW I am already building this for a while and push it to `quay.io/aminvakil/prometheus_bot` in https://github.com/aminvakil/prometheus_bot.

I can also help with this.

**Comment by kubitre** [comment]
@aminvakil I wanted the official build from this repository more maybe you will throw a PR into this repository without the deployment stage?

**Comment by aminvakil** [comment]
I will if maintainer thinks it's useful.

**Comment by ebarped** [comment]
I dont see how #85 solves this issue. Where is the docker image published in the github registry?

**Comment by aminvakil** [comment]
It hasn't. You can use this **unofficial repository** maintained by me from `quay.io/aminvakil/prometheus_bot`.

It's identical with this repository: https://github.com/inCaller/prometheus_bot/compare/master...aminvakil:master
