### ISSUE TITLE
Add support for topics

### ISSUE THREAD

**Issue by evgfilim1** [inCaller/prometheus_bot#92]
Telegram introduced [forums](https://telegram.org/blog/topics-in-groups-collectible-usernames): a chat that has multiple topics inside (technically these are one big chat). Bots also [have](https://core.telegram.org/bots/api-changelog#november-5-2022) support for this feature. I'd like to send a notification in the specific topic, but can't find anything to set it, so I guess it's not implemented.

Adding this feature is as simple as adding one more parameter named `message_thread_id` to the Telegram Bot API request.

**Comment by hryamzik** [comment]
Feel free to fire a PR.

**Comment by evgfilim1** [comment]
> Feel free to fire a PR.

I'd love to, but I don't really have time to dive into Golang (yet?)

**Comment by ZaytsevPavel8** [comment]
It would be great if this functionality could be implemented!

**Comment by silverwinter313** [comment]
@hryamzik please close issue

**Comment by evgfilim1** [comment]
Implemented in #101, merged in c675b6f9ee517f910c240d83e93a7a16aafc8319
